packages:
  - frontends/*
  - services/nitroapp

allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  esbuild: true
  protobufjs: true
  vue-demi: true

onlyBuiltDependencies:
  - '@parcel/watcher'
