/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BootstrapWrapper: typeof import('./../components/BootstrapWrapper.vue')['default']
    Card: typeof import('./../components/volt/Card.vue')['default']
    LoginBlock: typeof import('./../components/LoginBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoltWrapper: typeof import('./../components/VoltWrapper.vue')['default']
  }
}
