[project]
name = "mykube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "autometrics>=1.0.0",
    "django>=6.0.5",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.13.0",
    "django-redis>=6.0.0",
    "django-redis-cache>=1.8.0",
    "djangorestframework>=3.17.1",
    "gunicorn>=26.0.0",
    "psycopg[binary,pool]>=3.3.4",
    "python-dotenv>=1.2.2",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "factory-boy>=3.3.3",
    "pytest>=9.0.3",
    "pytest-aio>=2.1.7",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "pytest-env>=1.6.0",
]
