// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: insee.proto

package insee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InseeService_Siren_FullMethodName = "/insee.InseeService/Siren"
	InseeService_Siret_FullMethodName = "/insee.InseeService/Siret"
)

// InseeServiceClient is the client API for InseeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InseeServiceClient interface {
	Siren(ctx context.Context, in *SirenRequest, opts ...grpc.CallOption) (*SirenResponse, error)
	Siret(ctx context.Context, in *SiretRequest, opts ...grpc.CallOption) (*SiretResponse, error)
}

type inseeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInseeServiceClient(cc grpc.ClientConnInterface) InseeServiceClient {
	return &inseeServiceClient{cc}
}

func (c *inseeServiceClient) Siren(ctx context.Context, in *SirenRequest, opts ...grpc.CallOption) (*SirenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SirenResponse)
	err := c.cc.Invoke(ctx, InseeService_Siren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inseeServiceClient) Siret(ctx context.Context, in *SiretRequest, opts ...grpc.CallOption) (*SiretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SiretResponse)
	err := c.cc.Invoke(ctx, InseeService_Siret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InseeServiceServer is the server API for InseeService service.
// All implementations must embed UnimplementedInseeServiceServer
// for forward compatibility.
type InseeServiceServer interface {
	Siren(context.Context, *SirenRequest) (*SirenResponse, error)
	Siret(context.Context, *SiretRequest) (*SiretResponse, error)
	mustEmbedUnimplementedInseeServiceServer()
}

// UnimplementedInseeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInseeServiceServer struct{}

func (UnimplementedInseeServiceServer) Siren(context.Context, *SirenRequest) (*SirenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Siren not implemented")
}
func (UnimplementedInseeServiceServer) Siret(context.Context, *SiretRequest) (*SiretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Siret not implemented")
}
func (UnimplementedInseeServiceServer) mustEmbedUnimplementedInseeServiceServer() {}
func (UnimplementedInseeServiceServer) testEmbeddedByValue()                      {}

// UnsafeInseeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InseeServiceServer will
// result in compilation errors.
type UnsafeInseeServiceServer interface {
	mustEmbedUnimplementedInseeServiceServer()
}

func RegisterInseeServiceServer(s grpc.ServiceRegistrar, srv InseeServiceServer) {
	// If the following call panics, it indicates UnimplementedInseeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InseeService_ServiceDesc, srv)
}

func _InseeService_Siren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SirenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InseeServiceServer).Siren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InseeService_Siren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InseeServiceServer).Siren(ctx, req.(*SirenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InseeService_Siret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InseeServiceServer).Siret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InseeService_Siret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InseeServiceServer).Siret(ctx, req.(*SiretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InseeService_ServiceDesc is the grpc.ServiceDesc for InseeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InseeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insee.InseeService",
	HandlerType: (*InseeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Siren",
			Handler:    _InseeService_Siren_Handler,
		},
		{
			MethodName: "Siret",
			Handler:    _InseeService_Siret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "insee.proto",
}
