// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: login.proto

package insee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SirenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Siren         string                 `protobuf:"bytes,1,opt,name=siren,proto3" json:"siren,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SirenRequest) Reset() {
	*x = SirenRequest{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SirenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SirenRequest) ProtoMessage() {}

func (x *SirenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SirenRequest.ProtoReflect.Descriptor instead.
func (*SirenRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *SirenRequest) GetSiren() string {
	if x != nil {
		return x.Siren
	}
	return ""
}

type SirenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessName  string                 `protobuf:"bytes,1,opt,name=businessName,proto3" json:"businessName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SirenResponse) Reset() {
	*x = SirenResponse{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SirenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SirenResponse) ProtoMessage() {}

func (x *SirenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SirenResponse.ProtoReflect.Descriptor instead.
func (*SirenResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *SirenResponse) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

type SiretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Siren         string                 `protobuf:"bytes,1,opt,name=siren,proto3" json:"siren,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiretRequest) Reset() {
	*x = SiretRequest{}
	mi := &file_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiretRequest) ProtoMessage() {}

func (x *SiretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiretRequest.ProtoReflect.Descriptor instead.
func (*SiretRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{2}
}

func (x *SiretRequest) GetSiren() string {
	if x != nil {
		return x.Siren
	}
	return ""
}

type SiretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessName  string                 `protobuf:"bytes,1,opt,name=businessName,proto3" json:"businessName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiretResponse) Reset() {
	*x = SiretResponse{}
	mi := &file_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiretResponse) ProtoMessage() {}

func (x *SiretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiretResponse.ProtoReflect.Descriptor instead.
func (*SiretResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{3}
}

func (x *SiretResponse) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\x05insee\"$\n" +
	"\fSirenRequest\x12\x14\n" +
	"\x05siren\x18\x01 \x01(\tR\x05siren\"3\n" +
	"\rSirenResponse\x12\"\n" +
	"\fbusinessName\x18\x01 \x01(\tR\fbusinessName\"$\n" +
	"\fSiretRequest\x12\x14\n" +
	"\x05siren\x18\x01 \x01(\tR\x05siren\"3\n" +
	"\rSiretResponse\x12\"\n" +
	"\fbusinessName\x18\x01 \x01(\tR\fbusinessName2u\n" +
	"\fInseeService\x122\n" +
	"\x05Siren\x12\x13.insee.SirenRequest\x1a\x14.insee.SirenResponse\x121\n" +
	"\x05Siret\x12\x13.insee.SiretRequest\x1a\x13.insee.SiretRequestB\x18Z\x16services/goproto/inseeb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_login_proto_goTypes = []any{
	(*SirenRequest)(nil),  // 0: insee.SirenRequest
	(*SirenResponse)(nil), // 1: insee.SirenResponse
	(*SiretRequest)(nil),  // 2: insee.SiretRequest
	(*SiretResponse)(nil), // 3: insee.SiretResponse
}
var file_login_proto_depIdxs = []int32{
	0, // 0: insee.InseeService.Siren:input_type -> insee.SirenRequest
	2, // 1: insee.InseeService.Siret:input_type -> insee.SiretRequest
	1, // 2: insee.InseeService.Siren:output_type -> insee.SirenResponse
	2, // 3: insee.InseeService.Siret:output_type -> insee.SiretRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
